### ISSUE TITLE
4.25 TODO

### ISSUE THREAD

**Issue by ryugibo** [ryugibo/pinball-construction-kit#1]
- [x] Update engine version to 4.25
- [x] Fix always rebuild light map message
- [x] Apply UProperty, FProperty changes (https://docs.unrealengine.com/en-US/Support/Builds/ReleaseNotes/4_25/index.html#bookmarkuproperty)
- [x] Fix compile warning (Change DefaultBuildSettings to BuildSettingsVersion.V2)

**Comment by ryugibo** [comment]
```
2>[Upgrade]
2>[Upgrade] Using backward-compatible build settings. The latest version of UE4 sets the following values by default, which may require code changes:
2>[Upgrade]     bLegacyPublicIncludePaths = false                 => Omits subfolders from public include paths to reduce compiler command line length. (Previously: true).
2>[Upgrade]     ShadowVariableWarningLevel = WarningLevel.Error   => Treats shadowed variable warnings as errors. (Previously: WarningLevel.Warning).
2>[Upgrade]     PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs   => Set in build.cs files to enables IWYU-style PCH model. See https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/IWYU/index.html. (Previously: PCHUsageMode.UseSharedPCHs).
2>[Upgrade] Suppress this message by setting 'DefaultBuildSettings = BuildSettingsVersion.V2;' in PinballEditor.Target.cs, and explicitly overriding settings that differ from the new defaults.
2>[Upgrade]
```
